# Generated by Django 5.2.1 on 2025-05-20 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='8Cq5F2', max_length=10, unique=True, verbose_name='Код ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Переходы')),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_short_link', to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'короткая ссылка на рецепт',
                'verbose_name_plural': 'Короткие ссылки на рецепт',
            },
        ),
    ]
