# Generated by Django 5.2.1 on 2025-05-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshortlink',
            name='code',
            field=models.CharField(default='0F1LU3', max_length=10, unique=True, verbose_name='Код ссылки'),
        ),
    ]
